version: 2

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/ansible-lint.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/ansible-lint.tar | true
      - run:
          name: Build ansible-lint Docker image
          command: |
            docker build --cache-from=ansible-lint -t yokogawa/ansible-lint .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/ansible-lint.tar yokogawa/ansible-lint
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ansible-lint.tar
      - run:
          name: Run ansible-lint (test)
          command: |
            docker run -it --rm yokogawa/ansible-lint ansible-lint --version
      # use docker cloud/hub
      #- deploy:
      #    name: Push application Docker image
      #    command: |
      #      if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #        login="$(aws ecr get-login)"
      #        ${login}
      #        docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #        docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
      #      fi

