version: 2

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:19.03
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-python2-{{ .Branch }}
            - v1-python3-{{ .Branch }}
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/ansible-lint-python2.tar | true
            docker load -i /caches/ansible-lint-python3.tar | true
      - run:
          name: Build ansible-lint Docker image (python2)
          command: |
            docker build --cache-from=ansible-lint-python2 -t yokogawa/ansible-lint:ptyhon2 python2/
      - run:
          name: Build ansible-lint Docker image (python3)
          command: |
            docker build --cache-from=ansible-lint-python3 -t yokogawa/ansible-lint:ptyhon3 python3/
      - run:
          name: Run ansible-lint (test)
          command: |
            docker run -it --rm yokogawa/ansible-lint:python2 ansible-lint --version
            docker run -it --rm yokogawa/ansible-lint:python3 ansible-lint --version
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/ansible-lint-python2.tar yokogawa/ansible-lint:python2
            docker save -o /caches/ansible-lint-python3.tar yokogawa/ansible-lint:python3
      - save_cache:
          key: v1-python2-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ansible-lint-python2.tar
      - save_cache:
          key: v1-python3-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/ansible-lint-python3.tar

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
